
package com.tp_archi_distribuee.soapClient.client;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.3.7
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "HotelServiceReservationService", targetNamespace = "http://service.soap.tp_archi_distribuee.com/", wsdlLocation = "http://localhost:8081/Server_Oceania/Reservation?wsdl")
public class HotelServiceReservationService
    extends Service
{

    private static final URL HOTELSERVICERESERVATIONSERVICE_WSDL_LOCATION;
    private static final WebServiceException HOTELSERVICERESERVATIONSERVICE_EXCEPTION;
    private static final QName HOTELSERVICERESERVATIONSERVICE_QNAME = new QName("http://service.soap.tp_archi_distribuee.com/", "HotelServiceReservationService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8081/Server_Oceania/Reservation?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        HOTELSERVICERESERVATIONSERVICE_WSDL_LOCATION = url;
        HOTELSERVICERESERVATIONSERVICE_EXCEPTION = e;
    }

    public HotelServiceReservationService() {
        super(__getWsdlLocation(), HOTELSERVICERESERVATIONSERVICE_QNAME);
    }

    public HotelServiceReservationService(WebServiceFeature... features) {
        super(__getWsdlLocation(), HOTELSERVICERESERVATIONSERVICE_QNAME, features);
    }

    public HotelServiceReservationService(URL wsdlLocation) {
        super(wsdlLocation, HOTELSERVICERESERVATIONSERVICE_QNAME);
    }

    public HotelServiceReservationService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, HOTELSERVICERESERVATIONSERVICE_QNAME, features);
    }

    public HotelServiceReservationService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public HotelServiceReservationService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns HotelServiceReservationInterface
     */
    @WebEndpoint(name = "HotelServiceReservationPort")
    public HotelServiceReservationInterface getHotelServiceReservationPort() {
        return super.getPort(new QName("http://service.soap.tp_archi_distribuee.com/", "HotelServiceReservationPort"), HotelServiceReservationInterface.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns HotelServiceReservationInterface
     */
    @WebEndpoint(name = "HotelServiceReservationPort")
    public HotelServiceReservationInterface getHotelServiceReservationPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://service.soap.tp_archi_distribuee.com/", "HotelServiceReservationPort"), HotelServiceReservationInterface.class, features);
    }

    private static URL __getWsdlLocation() {
        if (HOTELSERVICERESERVATIONSERVICE_EXCEPTION!= null) {
            throw HOTELSERVICERESERVATIONSERVICE_EXCEPTION;
        }
        return HOTELSERVICERESERVATIONSERVICE_WSDL_LOCATION;
    }

}
