
package com.tp_archi_distribuee.soapClient.client;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.3.7
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "HotelServiceDisponibiliteService", targetNamespace = "http://service.soap.tp_archi_distribuee.com/", wsdlLocation = "http://localhost:8081/Server_Oceania/Disponibilite?wsdl")
public class HotelServiceDisponibiliteService
    extends Service
{

    private static final URL HOTELSERVICEDISPONIBILITESERVICE_WSDL_LOCATION;
    private static final WebServiceException HOTELSERVICEDISPONIBILITESERVICE_EXCEPTION;
    private static final QName HOTELSERVICEDISPONIBILITESERVICE_QNAME = new QName("http://service.soap.tp_archi_distribuee.com/", "HotelServiceDisponibiliteService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8081/Server_Oceania/Disponibilite?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        HOTELSERVICEDISPONIBILITESERVICE_WSDL_LOCATION = url;
        HOTELSERVICEDISPONIBILITESERVICE_EXCEPTION = e;
    }

    public HotelServiceDisponibiliteService() {
        super(__getWsdlLocation(), HOTELSERVICEDISPONIBILITESERVICE_QNAME);
    }

    public HotelServiceDisponibiliteService(WebServiceFeature... features) {
        super(__getWsdlLocation(), HOTELSERVICEDISPONIBILITESERVICE_QNAME, features);
    }

    public HotelServiceDisponibiliteService(URL wsdlLocation) {
        super(wsdlLocation, HOTELSERVICEDISPONIBILITESERVICE_QNAME);
    }

    public HotelServiceDisponibiliteService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, HOTELSERVICEDISPONIBILITESERVICE_QNAME, features);
    }

    public HotelServiceDisponibiliteService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public HotelServiceDisponibiliteService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns HotelServiceDisponibiliteInterface
     */
    @WebEndpoint(name = "HotelServiceDisponibilitePort")
    public HotelServiceDisponibiliteInterface getHotelServiceDisponibilitePort() {
        return super.getPort(new QName("http://service.soap.tp_archi_distribuee.com/", "HotelServiceDisponibilitePort"), HotelServiceDisponibiliteInterface.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns HotelServiceDisponibiliteInterface
     */
    @WebEndpoint(name = "HotelServiceDisponibilitePort")
    public HotelServiceDisponibiliteInterface getHotelServiceDisponibilitePort(WebServiceFeature... features) {
        return super.getPort(new QName("http://service.soap.tp_archi_distribuee.com/", "HotelServiceDisponibilitePort"), HotelServiceDisponibiliteInterface.class, features);
    }

    private static URL __getWsdlLocation() {
        if (HOTELSERVICEDISPONIBILITESERVICE_EXCEPTION!= null) {
            throw HOTELSERVICEDISPONIBILITESERVICE_EXCEPTION;
        }
        return HOTELSERVICEDISPONIBILITESERVICE_WSDL_LOCATION;
    }

}
