
package com.tp_archi_distribuee.soapClient.client;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.3.7
 * Generated source version: 2.2
 * 
 */
@WebService(name = "HotelServiceReservationInterface", targetNamespace = "http://service.soap.tp_archi_distribuee.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface HotelServiceReservationInterface {


    /**
     * 
     * @param arg3
     * @param arg2
     * @param arg5
     * @param arg4
     * @param arg1
     * @param arg0
     * @param arg6
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "effectuerReservation", targetNamespace = "http://service.soap.tp_archi_distribuee.com/", className = "com.tp_archi_distribuee.soapClient.client.EffectuerReservation")
    @ResponseWrapper(localName = "effectuerReservationResponse", targetNamespace = "http://service.soap.tp_archi_distribuee.com/", className = "com.tp_archi_distribuee.soapClient.client.EffectuerReservationResponse")
    @Action(input = "http://service.soap.tp_archi_distribuee.com/HotelServiceReservationInterface/effectuerReservationRequest", output = "http://service.soap.tp_archi_distribuee.com/HotelServiceReservationInterface/effectuerReservationResponse")
    public String effectuerReservation(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        int arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        String arg2,
        @WebParam(name = "arg3", targetNamespace = "")
        String arg3,
        @WebParam(name = "arg4", targetNamespace = "")
        String arg4,
        @WebParam(name = "arg5", targetNamespace = "")
        String arg5,
        @WebParam(name = "arg6", targetNamespace = "")
        CreditCard arg6);

}
