
package com.tp_archi_distribuee.soapClient.client;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.3.7
 * Generated source version: 2.2
 * 
 */
@WebService(name = "HotelServiceDisponibiliteInterface", targetNamespace = "http://service.soap.tp_archi_distribuee.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface HotelServiceDisponibiliteInterface {


    /**
     * 
     * @param arg3
     * @param arg2
     * @param arg5
     * @param arg4
     * @param arg1
     * @param arg0
     * @return
     *     returns java.util.List<com.tp_archi_distribuee.soapClient.client.Offre>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "consulterDisponibilite", targetNamespace = "http://service.soap.tp_archi_distribuee.com/", className = "com.tp_archi_distribuee.soapClient.client.ConsulterDisponibilite")
    @ResponseWrapper(localName = "consulterDisponibiliteResponse", targetNamespace = "http://service.soap.tp_archi_distribuee.com/", className = "com.tp_archi_distribuee.soapClient.client.ConsulterDisponibiliteResponse")
    @Action(input = "http://service.soap.tp_archi_distribuee.com/HotelServiceDisponibiliteInterface/consulterDisponibiliteRequest", output = "http://service.soap.tp_archi_distribuee.com/HotelServiceDisponibiliteInterface/consulterDisponibiliteResponse")
    public List<Offre> consulterDisponibilite(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        String arg2,
        @WebParam(name = "arg3", targetNamespace = "")
        Object arg3,
        @WebParam(name = "arg4", targetNamespace = "")
        Object arg4,
        @WebParam(name = "arg5", targetNamespace = "")
        int arg5);

}
